### ISSUE TITLE
Question: how about V17

### ISSUE THREAD

**Issue by SanderElias** [hapinessjs/hapiness#73]
Is hapi V17 going to be supported? If so, what's the (if known!) the timeframe for that?

**Comment by akanass** [comment]
First thanks for your question and second, yes it’ll be supported as soon as possible.

We’re working on it but this project is maintained with our job and we need to find time to do it.

Latest version of `HapiJS` breaks many things so it’ll take time to adapt and be sure all works fine.

But framework works fine currently and you can use it :)

We will give to you the information when migration will be done.
